services:
  app:
    image: flask-app
    ports:
      - "6000:5000"
    links:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=camp2016
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017